# Generated by Django 4.1.5 on 2023-01-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrecord",
            name="project_detail",
            field=models.CharField(blank=True, max_length=1000, verbose_name="案件詳細"),
        ),
    ]
